### ISSUE TITLE
when add a node(Monitor existing cluster),it said “failed to install node”

### ISSUE THREAD

**Issue by LoongKK** [codership/galera-manager-support#108]
Monitor existing cluster.
 when I add a node,it said “failed to install node”
(details:)
```
msg: failed to install node
stackTrace:
  - "github.com/codership/galera-manager/pkg/internal/mgmt.(*Nodes).Create.func2\n\t/go/pkg/internal/mgmt/nodes.go:166"
  - "github.com/codership/galera-manager/pkg/internal/jobs.(*Processor).Execute.func1\n\t/go/pkg/internal/jobs/processor.go:106"
  - "runtime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1695"
wrapped:
  msg: selected host already has a node installed
  stackTrace:
    - "github.com/codership/galera-manager/pkg/internal/mgmt/units.(*Node).Install\n\t/go/pkg/internal/mgmt/units/node.go:361"
    - "github.com/codership/galera-manager/pkg/internal/mgmt.(*Nodes).Create.func2\n\t/go/pkg/internal/mgmt/nodes.go:163"
    - "github.com/codership/galera-manager/pkg/internal/jobs.(*Processor).Execute.func1\n\t/go/pkg/internal/jobs/processor.go:106"
    - "runtime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1695"
    - "github.com/codership/galera-manager/pkg/internal/mgmt/units.(*Node).assertNoInstallation\n\t/go/pkg/internal/mgmt/units/node.go:1201"
    - "github.com/codership/galera-manager/pkg/internal/mgmt/units.(*Node).Install\n\t/go/pkg/internal/mgmt/units/node.go:359"
    - "github.com/codership/galera-manager/pkg/internal/mgmt.(*Nodes).Create.func2\n\t/go/pkg/internal/mgmt/nodes.go:163"
    - "github.com/codership/galera-manager/pkg/internal/jobs.(*Processor).Execute.func1\n\t/go/pkg/internal/jobs/processor.go:106"
    - "runtime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1695"
  fields:
    cluster-id: '5'
    node-id: '4'
    output: >-
      {"host":{"id":"3","name":"node1","type":"unmanaged","system":"debian:12","privateKey":"-----BEGIN
      RSA PRIVATE
      KEY-----\nMIIJKQIBAAKCAgEAoAy/+4jGr4tiHGoYtrW2IbRmrLmc3D6Ch1XqRtlrOJBsGbRn\nufBtiTfBpWeEtmQSGtN0y8VITFXyoO9JbJkvW9jYp4GeAo+RQ7wST07jRWVByn2z\nQR5S1JwDzYPGKadYHOosRuyKzClB6cCo4a5WHGCWcK50F1RMEE06A2Bd9m6Ok46B\nBSe9moy0oT0HuqxCh5eRcisDKe3euMe4wTP7g99Mr8+4bLrEWbswx06kKji/UIIY\nUVjfRvu8lUOKDERyoPCJU6pWTJM0uZYq+akptgWXSpdKts/9KA4AhWfgbgD3cGQ9\nGx395VpEzSHpMBoilkM0eaiabiXXL+4oW+7s19A4FYVZ47fwbwJ/L+WVo4x6n6XI\n7l4E8bfxgbmex7AoSgKE8HBqsabm31l9L5GORSN+2eKmw7vCYSnA5WxN5N14FquM\nMjGgmCmh77O4UCCuVunq8cLpfVjOJH6IHm/60SX+ybdCi5aWrO1/eYEuh4V27QdI\no8pwI+t6Os7iZs/JwGwvqQQ9dcv6PjuUABJesLXrbIsabkJ4c7jOB3VxT5Vjzj4+\nS6RZO3Jo09r2Xf0DYjkgVFpi98VTPDqYkp490bMrQTb1SoBNDFhlSWTZUVMKwjH0\nBdDhYpIb8bBNwiSlfMIlUr5ohOAvABgaltoWxw2cdc/bug/vFDvnzCwqRSUCAwEA\nAQKCAgBDdhxWAcj9pVqtb2sLWHx0qH2+wF4F17NdKDGfu3UeWoG2M/yku1rwQ7gz\n5/Zgir224PqSCY333yJuA26Hf+oeZMCtmkzn92vbiSKOm0ngrlWU7HbqM8XmJ/zS\nW4Djfc3+IhaXroyykZFe3f5RYhKZ03yV8nKsgrOtC2AwnCX/AYrHV4G6ko2w3y4j\n6H2hiYphbNm5rbefrMv8RvLxPN//Ldg9Iukxq2eoCub8m4FG6rR5Uty9LSCv4twS\nbm15zkAi5kB8K4hErqfCsjFbGpqiRqkGn862T+T9RSmjEa3fsDib/yRikbm7OtlV\nPb30sI9zltA/l3nAg+K4KUKJvaPGiSlrh3QlSAt1HJCfSh+xRM2WiVDDsiS3pGz2\nVrPC138vbOLPYRU8VurdudO4GjlI7rr5N8yW4fDn+g95lWIkWhmK+IFre59wyLkW\ns3jEttj3ES+HCVkCLWtFi29oaUuCEBGG0uSS5k/GFiqhY290mcSxDWogyOQNHEXt\nv2dkhUBoRxwh2yv47jYypgY1OTt3AAHIsHQrYKDnQF1bLErxqMUAT1+CQ9HtYWkA\nA/+vOaN8KacHJvp5lOT4TBU5BxLwW0Im3H+fGZVNYEWHvETpu7DOAmtWVCf0v1A2\nPkXXOPp41TsHl3Uhh/LbvbAJQPcz82psnYg5JTtk3CxnzWa1AQKCAQEAzlSNmInA\n3AqZJOGA3AauuOoK6Qttzb1WL3Wsk1TMyMIZK1oXhvnNt4KbY1qhxTEoR9UaQZli\n5oOBpoaBageNXfID6IieyiHd9lHVQ2q2JgkQmJgXJs8faFpxSWCJAVcnmkm8Zvss\n2lj0RQjyhgG3aEze85xqS1ypCaZGDIrrAHKa+drK7WGq6iwasSUTvmgH/aZsfzR+\nb7jiXXOtHFv4UbrZplT/lxqd1gQW9n4TUP2Z5Pd5Tz38Znrx9sEuB/DmEZWYL+Ga\nb76YKuY/LLpOmRJ6YxgKBlHeMd0ZeLgdUmtjUQqvIrMDK4C0f8VCZe92QcKcgEyX\nEu4fleI1Gb2xrQKCAQEAxpQV0WKEA//1X9L0G+FK7wGvb/B2hygoA86xmnHHMwBo\noQaN2QN8Zj4wfmNVP+7D90fP6fNeLXjn3N3VBmRaDb2hT50nVn2AEwuazd7pPJOA\nMymOiR+GIwm6jy/aAPPGWjlAR6Wx0ViEx74mLJ4YnCbESiKQ86apzwrytT7oTjhA\n4d51ons569JuTqt20uHS8lAKVLsyk9bZL2uYKgXda6IM8cTOSDhNgq62/Twisvdr\niLG1LWGfOOZBD+SwwvgcgU+naLs1Ds97nTIohnE/qaLIe4Pmca89bqgR1jPz3RwO\neNpQ/rbU/YSrYHjaHbQ1C1QaVKE9G82h6f67iAWAWQKCAQEAliiE0AFYoQr5fxS6\nIeafG6YAgK+3nqZvZaS/Do4FZwmTJbCwNKPx6d6cVYcs+gSXaweUzy7hAh+sqFN1\nNYP/huJNo9phrXtOPSg7C5BKtY2dTWBKYQ0Vr206ywr9SkNyZ9/HxC6B6voX83Ha\nhloTb02aaDJqTSRHROWETzZ+ZloBnVp0mqOcrkWgu1DfeI/fWOLYTQ8YARjNbPN1\nhZENO/W+1kU/qWlOeuWJDKSeTC/z4uWTnG7hFHffRhQ6+r5/wUZcdmQ6b56GwZnF\nWjjQYKhI93sUOJs2GJXvJqLffA75PY6H/LnI0c0eD2qwsty99Ie8O8cBn147EGqK\n+IvMFQKCAQEAqlXsQSdYRnYQbJnvetrOBCZV7pc9lMIFUP7Dqc9fJ4h6N2X/1t7+\nnlVKE5/xSF3vCvY2il+PsUG84eAHEuyRsqeu7zPGwpH0gmG58E39k1CS70/+S/EW\nhoeZ16kcPyTcSBhD4zFmTkS34P5ikHMseQVn6o+r9tRHZKnnd0D20+G9BgJktXMu\nQ/LFXAYIbuv2npO5yOSqhdYNhneslp9hRypCIEDJEXn6QtbLcH1c5lcFjsOgvcS3\nZ39a398zIIrjKKjC2Tt8T6/6QOT9jhUmnsRbZFfIHExNTdYtNqhpzoh6gYADafo6\nyRw8RQxlTIV/2q/RxjZozKie8rDm+858QQKCAQB8B7asSF1DL7OvCPL0rb4Pyk44\nqjhaKQBZP4plwG7d2K6d4ElTDmjJaovHJD7Jfsp5P9He66ogmyusqLhhcrgg9Yti\n8dK4xjyldOAw5W4lQlQ7Yv0TJPSUQZbnAp4LqE8N/dAaCVivmxvteKWlTOMUEVs+\nkc1e9xLzjuJgpqQ39bSaMla/TDN9IrOIXlWK3BiWd1iJ6F12CAxJr4pQLNLTnqLC\nsxmL/kfvDdwJuEDVpwp8t7UZAEhbF3cKmuhNbLOjem5YCM2X53dgnBQIRIOIhq33\nqmXIq0FdHJDbX4ZF3aYRZv7Lz26PFhhbN4viopF6U3C2wIX+E+ZaE6RsDtkD\n-----END
      RSA PRIVATE KEY-----\n","authorizedKeys":["ssh-rsa
      AAAAB3NzaC1yc2EAAAADAQABAAACAQCgDL/7iMavi2Icahi2tbYhtGasuZzcPoKHVepG2Ws4kGwZtGe58G2JN8GlZ4S2ZBIa03TLxUhMVfKg70lsmS9b2NingZ4Cj5FDvBJPTuNFZUHKfbNBHlLUnAPNg8Ypp1gc6ixG7IrMKUHpwKjhrlYcYJZwrnQXVEwQTToDYF32bo6TjoEFJ72ajLShPQe6rEKHl5FyKwMp7d64x7jBM/uD30yvz7hsusRZuzDHTqQqOL9QghhRWN9G+7yVQ4oMRHKg8IlTqlZMkzS5lir5qSm2BZdKl0q2z/0oDgCFZ+BuAPdwZD0bHf3lWkTNIekwGiKWQzR5qJpuJdcv7ihb7uzX0DgVhVnjt/BvAn8v5ZWjjHqfpcjuXgTxt/GBuZ7HsChKAoTwcGqxpubfWX0vkY5FI37Z4qbDu8JhKcDlbE3k3XgWq4wyMaCYKaHvs7hQIK5W6erxwul9WM4kfogeb/rRJf7Jt0KLlpas7X95gS6HhXbtB0ijynAj63o6zuJmz8nAbC+pBD11y/o+O5QAEl6wtetsixpuQnhzuM4HdXFPlWPOPj5LpFk7cmjT2vZd/QNiOSBUWmL3xVM8OpiSnj3RsytBNvVKgE0MWGVJZNlRUwrCMfQF0OFikhvxsE3CJKV8wiVSvmiE4C8AGBqW2hbHDZx1z9u6D+8UO+fMLCpFJQ==
      MariaDB_Cluster@20240625160907"],"databaseSizeGiB":60,"hostTypeSpecific":{"enableFirewall":false},"segment":0,"clusterID":"5","ssh":{"address":"192.168.100.111","port":"22"},"db":{"address":"192.168.100.111","port":"3306"},"deploymentStatus":"ok","createdBy":"","createdAt":"2024-06-25T17:20:06.642150325+08:00"},"node":{"id":"3","name":"node1","clusterID":"5","dbEngine":"mariadb:10.11","userConfig":"","settings":{"logs":{"generalLog":{"path":"/var/log/mysql/general.log","enabled":false},"slowLog":{"path":"/var/log/mysql/mysql-slow.log","enabled":false},"errorLog":{"path":"/var/log/mysql/error.log","enabled":false}}},"deploymentStatus":"error","deploymentStatusReason":"selected
      host already has a node
      installed","unmanaged":true,"createdBy":"","createdAt":"2024-06-25T17:20:06.683158753+08:00","cert":null,"privKey":null}}
```

[galera] in  /etc/mysql/mariadb.conf.d/50-server.cnf:
```
[galera]
wsrep_on=ON
wsrep_provider=/usr/lib/galera/libgalera_smm.so
wsrep_cluster_address="gcomm://192.168.100.111,192.168.100.112,192.168.100.113"
binlog_format=row
default_storage_engine=InnoDB
innodb_autoinc_lock_mode=2
bind-address=0.0.0.0
wsrep_cluster_name="MariaDB_Cluster"
wsrep_node_address="192.168.100.111"
```
