### ISSUE TITLE
filebeat.yml is incorrectly filled when adding an existing node

### ISSUE THREAD

**Issue by ronnybremer** [codership/galera-manager-support#29]
After adding a existing CentOS host I found this potential error in filebeat.yml:
```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - ABORT_SERVER^M
stderr^M
3^M

    - /var/lib/mysql/node1.log^M

    - /var/lib/mysql/node1-slow.log^M
```

Somehow that doesn't look right to me and filebeat complains during startup.

**Comment by denisgcm** [comment]
Thank you for reaching out to us. We identified a bug. For now you can fix it manually:

```yaml
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/lib/mysql/error.log
    - /var/lib/mysql/node1.log
    - /var/lib/mysql/node1-slow.log
```

And then restart filebeat. Please let me know if it worked for you.
